"""Self-contained HTML report generator.

Assembles the dashboard's headline numbers, plain-English findings, anomaly
summary, charts, and model results into a single standalone .html file the user
can download and open in any browser (and "Print → Save as PDF"). Plotly is
pulled from CDN so the file stays small while charts remain interactive.
"""
from __future__ import annotations

from datetime import datetime

import pandas as pd
from jinja2 import Template

_TEMPLATE = Template(
    """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>{{ title }}</title>
<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
<style>
 body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;color:#1f2933;background:#f5f7fa}
 .wrap{max-width:1000px;margin:0 auto;padding:32px}
 h1{margin:0 0 4px} .sub{color:#7b8794;margin-bottom:28px}
 h2{border-bottom:2px solid #e4e7eb;padding-bottom:6px;margin-top:40px}
 .cards{display:flex;flex-wrap:wrap;gap:14px;margin:18px 0}
 .card{background:#fff;border:1px solid #e4e7eb;border-radius:10px;padding:16px 20px;min-width:140px;box-shadow:0 1px 2px rgba(0,0,0,.04)}
 .card .k{font-size:12px;color:#7b8794;text-transform:uppercase;letter-spacing:.04em}
 .card .v{font-size:24px;font-weight:700;margin-top:4px}
 table{border-collapse:collapse;width:100%;background:#fff;font-size:13px}
 th,td{border:1px solid #e4e7eb;padding:6px 10px;text-align:left}
 th{background:#f0f4f8} tr:nth-child(even){background:#fafbfc}
 .chart{background:#fff;border:1px solid #e4e7eb;border-radius:10px;padding:10px;margin:16px 0}
 ul{background:#fff;border:1px solid #e4e7eb;border-radius:10px;padding:16px 16px 16px 36px}
 .alert{background:#fff7ed;border:1px solid #fed7aa;border-radius:10px;padding:16px 20px}
 footer{color:#9aa5b1;font-size:12px;margin-top:48px;text-align:center}
 code{background:#eef2f6;padding:1px 5px;border-radius:4px}
</style></head><body><div class="wrap">
<h1>{{ title }}</h1>
<div class="sub">Generated by Lumen on {{ generated }}</div>

<h2>At a glance</h2>
<div class="cards">
{% for c in cards %}<div class="card"><div class="k">{{ c.label }}</div><div class="v">{{ c.value }}</div></div>{% endfor %}
</div>

{% if findings %}<h2>Key findings</h2><ul>{% for f in findings %}<li>{{ f }}</li>{% endfor %}</ul>{% endif %}

{% if anomaly %}<h2>Records to review</h2>
<div class="alert"><strong>{{ anomaly.flagged }}</strong> of {{ anomaly.records }} records
({{ anomaly.flagged_pct }}%) look unusual and may be worth checking.
{% if anomaly.drivers %}<ul style="background:none;border:none;margin-top:8px">{% for d in anomaly.drivers %}<li>{{ d }}</li>{% endfor %}</ul>{% endif %}</div>{% endif %}

{% if quality_flags %}<h2>Things to clean up</h2><ul>{% for f in quality_flags %}<li>{{ f }}</li>{% endfor %}</ul>{% endif %}

{% if cleaning_steps %}<h2>Cleaning steps applied ({{ cleaning_steps|length }})</h2><ul>{% for s in cleaning_steps %}<li>{{ s }}</li>{% endfor %}</ul>{% endif %}

{% for c in charts %}<h2>{{ c.title }}</h2><div class="chart">{{ c.html }}</div>{% endfor %}

{% if leaderboard %}<h2>Prediction model results</h2>{{ leaderboard }}
<p>Best model: <strong>{{ best_model }}</strong> ({{ task }}).</p>{% endif %}

<h2>Field details</h2>
{{ profile_table }}

<footer>Lumen — automated data analysis platform</footer>
</div></body></html>"""
)


def build_report(
    *,
    title: str,
    cards: list[dict],
    profile_df: pd.DataFrame,
    findings: list[str] | None = None,
    anomaly: dict | None = None,
    quality_flags: list[str] | None = None,
    cleaning_steps: list[str] | None = None,
    figures: list[tuple[str, "object"]] | None = None,
    leaderboard_df: pd.DataFrame | None = None,
    best_model: str | None = None,
    task: str | None = None,
) -> str:
    """Return a complete HTML document as a string. `figures` is [(title, fig)]."""
    charts = []
    for fig_title, fig in (figures or []):
        charts.append({"title": fig_title,
                       "html": fig.to_html(full_html=False, include_plotlyjs=False)})

    return _TEMPLATE.render(
        title=title,
        generated=datetime.now().strftime("%Y-%m-%d %H:%M"),
        cards=cards,
        findings=findings or [],
        anomaly=anomaly,
        profile_table=profile_df.to_html(index=False, border=0),
        quality_flags=quality_flags or [],
        cleaning_steps=cleaning_steps or [],
        charts=charts,
        leaderboard=leaderboard_df.to_html(index=False, border=0) if leaderboard_df is not None else None,
        best_model=best_model,
        task=task,
    )
